version: '3.8'

services:

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: asset_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - asset-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5ss
      timeout: 5s
      retries: 5
      
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - asset-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  security-service:
    build: ./security-service
    container_name: security-service
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - asset-network
    environment:
      SPRING_PROFILES_ACTIVE: docker

  asset-service:
    build: ./asset-service
    container_name: asset-service
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - asset-network
    environment:
      FLASK_ENV: production
      MONGO_URI: mongodb://root:example@mongodb:27017/asset_db?authSource=admin 
      SECURITY_SERVICE_URL: http://security-service:8080  
      REDIS_URL: redis://redis:6379/0  
      PYTHONUNBUFFERED: 1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

volumes:
  mongo_data:

networks:
  asset-network:
    driver: bridge