version: "3.9"

services:
  app:
    build: .
    container_name: asset-service
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - MONGO_URI=mongodb://root:example@mongodb:27017/asset_db?authSource=admin
      - REDIS_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
    networks:
      - asset-network

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - redis_data:/data
    networks:
      - asset-network

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: asset_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - asset-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet -u root -p example localhost:27017/asset_db
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
  mongo_data:

networks:
  asset-network:
    driver: bridge