version: '3.8'

services:
  security-service:
    build:
      context: ./security-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"  # Debug port (remove in production)
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - asset-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

networks:
  asset-network:
    driver: bridge
    name: security-service-network