name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-test-asset-service:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6.0
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        ports:
          - 27017:27017
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          pip install -r asset-service/requirements.txt
          pip install flake8 pytest
          pip install pytest-mock

      - name: Lint Python code
        run: flake8 asset-service/ --exclude=venv,__pycache__

      - name: Run Python tests
        env:
          MONGO_URI: "mongodb://root:example@localhost:27017/asset_db?authSource=admin"
          REDIS_URL: "redis://localhost:6379/0"
        run: |
          pytest -v asset-service/tests/

  test-security-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build & Test Spring Boot App
        working-directory: ./security-service
        run: mvn clean verify

  build-docker-images:
    runs-on: ubuntu-latest
    needs: [lint-test-asset-service, test-security-service]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Asset Service
        uses: docker/build-push-action@v4
        with:
          context: ./asset-service
          tags: asset-service:latest

      - name: Build Security Service
        uses: docker/build-push-action@v4
        with:
          context: ./security-service
          tags: security-service:latest
